name: YAML to ENV
description: |
  Parse all keys & values out of a YAML file, adding them to the $GITHUB_ENV file

branding:
  icon: copy
  color: blue

inputs:
  yaml-file:
    required: true
    description: "Filepath to YAML to parse"
  yq-version:
    required: false
    default: "4.27.5"
    description: "Version of yq to install, if not already in path.  Tested with >= 4.25."
  debug:
    required: false
    default: "false"
    description: "Enable debug logging.  This WILL print un-masked secrets to stdout, so use with caution."

outputs:
  yq-installed:
    description: "'true' if yq was installed by this action"
    value: "${{ steps.yq-check.outputs.found == 'false' }}"

runs:
  using: composite
  steps:
    - name: Check yaml file existence
      shell: bash
      run: |
        if ! [ -f '${{ inputs.yaml-file }}' ]; then
          echo 'Configured YAML file "${{ inputs.yaml-file }}" not found'
          exit 1
        fi

    - name: Check for yq
      id: yq-check
      shell: bash +e {0}
      run: |
        _yq_bin="$(which yq)"
        if [ -f "${_yq_bin}" ]; then
          echo "found=true" >> $GITHUB_OUTPUT
        else
          echo "found=false" >> $GITHUB_OUTPUT
        fi

    - name: 'Install yq (${{ inputs.yq-version }})'
      uses: chrisdickinson/setup-yq@latest
      if: steps.yq-check.outputs.found == 'false'
      with:
        yq-version: '${{ inputs.yq-version }}'

    - name: YAML to ENV
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/yaml-to-env.sh
      env:
        YAMLTOENV_DEBUG: '${{ inputs.debug }}'
        YAMLTOENV_YAML_FILE: '${{ inputs.yaml-file }}'
